### ISSUE TITLE
Unverified user unable to unlock points.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeosgov_frontend#23]
8/8/22 freeosgov2 frontend v0.1.17 account: dannydevito type 'd'. Iteration=461088
System record: Unlock%=15% Unlockiteration=4601088 Locked bal=50.0000 POINTs
Unable to unlock points as Unlock button was disabled. Expecting to be able to unlock 15% of locked bal
![Freeos App 08-08-2022 11-16-42](https://user-images.githubusercontent.com/77765830/183315243-352b65bc-d25d-4536-bc7b-1bd925f5a955.png)
![Account - Proton Testnet 08-08-2022 11-17-08](https://user-images.githubusercontent.com/77765830/183315247-d79ee421-1f1b-4fae-ab69-d50874f64993.png)
.

**Comment by conorseed** [comment]
@judytan21 - pushed a potential fix in v0.1.18. Couldn't test on my end, but should work! Let me know how it goes.

**Comment by judytan21** [comment]
9/8/22 Retest. freeosgov2 frontend v0.1.18 account: dannydevito type 'd' unverified. Iteration=461112
System record: Unlock%=15% Unlockiteration=4601112 Failsafe=0 Locked bal=50.0000 POINTs
Unable to unlock points as Unlock button was disabled. Expecting to be able to unlock 15% of locked bal
Not fixed.
Same results when testing with another unverified user powderblue type 'e'.
![Account - Proton Testnet 09-08-2022 11-03-17](https://user-images.githubusercontent.com/77765830/183529530-725b945f-de79-4a03-8b5c-f57ca82f3fc6.png)
![Freeos App 09-08-2022 11-03-55](https://user-images.githubusercontent.com/77765830/183529551-7223aceb-a7e0-4dd2-a492-f2cff5296432.png)
![Freeos App 09-08-2022 11-05-20](https://user-images.githubusercontent.com/77765830/183529586-3a9da59d-c588-4882-913e-f82a4011d06f.png)
.

**Comment by conorseed** [comment]
v0.1.19 should fix this - third times the charm ;)

**Comment by judytan21** [comment]
10/8/22 Retest. freeosgov2 frontend v0.1.19. dannydevito unverified unregisterd.
Sorry Conor! Still didn't work. Unlock 1% button enabled. Correct. Click to unlock. Assertion message: Participant record not found. Not fixed.
<img width="459" alt="Screen Shot 2022-08-10 at 2 14 36 PM" src="https://user-images.githubusercontent.com/77765830/183795813-e08db96b-de9c-4072-8583-2ed6cdf844f0.png">

**Comment by judytan21** [comment]
10/8/22 Retest in backend. v0.9.37. 
Hey Tom, reassigning this issue to you as I tested the scenario in the backend and it failed with assert message: Participant record not found.
![Account - Proton Testnet 10-08-2022 14-33-27](https://user-images.githubusercontent.com/77765830/183798096-3bbd748c-6e5d-48bb-8984-49be8aa5f3bc.png)
.

**Comment by judytan21** [comment]
23/8/22 freeosgov2 frontend v0.2.2 backend v0.9.42 iter 461450 
dannydevito, unverified type 'd' No participant record was able to unlock 21% of locked points. Fixed.
